---
title: "Olympic Games"
format: 
  dashboard:
    orientation: columns
    nav-buttons: [github]
    github: https://github.com/posit-conf-2024/olympicdash
logo: images/olympics-logo.svg
embed-resources: true
logo-alt: "Olympics logo with multicolored circles."
---

```{r}
#| label: load-packages

library(tidyverse)
library(gt)
```

```{r}
#| label: load-data

olympics <- read_csv("data/olympics.csv")
```

```{r}
#| label: prep-data

olympics <- olympics |>
  filter(
    season == "Summer",
    !is.na(medal)
  ) |>
  separate_wider_delim(
    cols = team, 
    names = c("team", "suffix"), 
    delim = "-", 
    too_many = "merge", 
    too_few = "align_start"
  ) |>
  select(-suffix) |>
  mutate(medal = fct_relevel(medal, 
                             "Gold", 
                             "Bronze", 
                             "Silver")
         )
```

## Column

### Medals by Sport

```{r}
#| label: medals-by-sport

olympics |>
  mutate(
    sport = fct_lump_n(sport, n = 15),
    sport = fct_infreq(sport),
    sport = fct_rev(sport)
  ) |>
  ggplot(aes(y = sport, fill = medal)) +
  geom_bar() +
  labs(
    x = NULL,
    y = NULL,
    fill = "Medal"
  ) +
  theme_bw() +               
  guides(fill = guide_legend(reverse = TRUE)) +
  theme(
    legend.position = "inside",
    legend.position.inside = c(0.75, 0.15),
    legend.direction = "horizontal",
    legend.background = element_rect(
      fill = "white",
      color = "gray70"
      ),
  legend.box.background = element_blank()
)
```

### 

::: {.card title="Medals by Year"}

Due to WWII, no Olympic games were held in 1940 and 1944. 

```{r}
#| label: medals-by-year

olympics |>
  count(year, medal) |>
  ggplot(aes(x = year, y = n, color = medal)) +
  geom_point(size = 1) +
  geom_line() +
  labs(
    x = "Year",
    y = NULL,
    color = ""
  ) +
  theme_bw() +                     
  guides(fill = guide_legend(reverse = TRUE)) +
  theme(
    legend.position = "inside",
    legend.position.inside = c(0.2, 0.8),
    legend.direction = "horizontal",
    legend.background = element_rect(
      fill = "white",
      color = "gray70"
      ),
  legend.box.background = element_blank()
)
```
:::  

## Column

### Row {height="30%"}

```{r}
most_gold <- olympics |>
  filter(medal == "Gold") |>
  count(team, sort = TRUE) |>
  slice_head(n = 1)

most_silver <- olympics |>
  filter(medal == "Silver") |>
  count(team, sort = TRUE) |>
  slice_head(n = 1)

most_bronze <- olympics |>
  filter(medal == "Bronze") |>
  count(team, sort = TRUE) |>
  slice_head(n = 1)
```


::: {.valuebox icon="award-fill" color="#D4AF37"}
Most Golds:

`{r} most_gold$n`

`{r} most_gold$team`
:::

::: {.valuebox icon="award-fill" color="#C0C0C0"}
Most Silver:

`{r} most_silver$n`

`{r} most_silver$team`
:::

::: {.valuebox icon="award-fill" color="#CD7F32"}
Most Bronze:

`{r} most_bronze$n`

`{r} most_bronze$team`
:::

### Row  {height="80%"}

::: {.panel-tabset}

## Top 30 total medals

</br>

Teams sorted in descending order of total medals.

```{r}
#| label: top-30

olympics |>
  count(team, medal) |>
  pivot_wider(
    names_from = medal,
    values_from = n,
    values_fill = 0
  ) |>
  mutate(Total = Bronze + Gold + Silver) |>
  slice_max(n = 30, order_by = Total) |>
  rename(Team = team) |> 
  select(Team, Gold, Silver, Bronze) |> 
  gt() |>
  data_color(
    columns = Gold,
    colors = scales::col_numeric(c("#FFF7CC", "#D4AF37"), domain = NULL)
  ) |>
  data_color(
    columns = Silver,
    colors = scales::col_numeric(c("#F2F2F2", "#C0C0C0"), domain = NULL)
  ) |>
  data_color(
    columns = Bronze,
    colors = scales::col_numeric(c("#F5E1D3", "#CD7F32"), domain = NULL)
  )
```

## Bottom 30 total medals

</br>

Teams sorted in descending order of total medals.

```{r}
#| label: bottom-30

olympics |>
  count(team, medal) |>
  pivot_wider(
    names_from = medal,
    values_from = n,
    values_fill = 0
  ) |>
  mutate(Total = Bronze + Gold + Silver) |>
  slice_min(n = 30, order_by = Total) |>
  rename(Team = team) |> 
  select(Team, Gold, Silver, Bronze) |> 
  gt() |>
  data_color(
    columns = Gold,
    colors = scales::col_numeric(c("#FFF7CC", "#D4AF37"), domain = NULL)
  ) |>
  data_color(
    columns = Silver,
    colors = scales::col_numeric(c("#F2F2F2", "#C0C0C0"), domain = NULL)
  ) |>
  data_color(
    columns = Bronze,
    colors = scales::col_numeric(c("#F5E1D3", "#CD7F32"), domain = NULL)
  )
```

:::